#!/bin/bash
until [ $(getprop sys.boot_completed). = 1. ]; do sleep 1; done
pm grant "com.google.android.syncadapters.contacts" android.permission.ACCESS_NETWORK_STATE
pm grant "com.google.android.syncadapters.contacts" android.permission.GET_ACCOUNTS
pm grant "com.google.android.syncadapters.contacts" android.permission.INTERACT_ACROSS_USERS
pm grant "com.google.android.syncadapters.contacts" android.permission.INTERNET
pm grant "com.google.android.syncadapters.contacts" android.permission.READ_CONTACTS
pm grant "com.google.android.syncadapters.contacts" android.permission.READ_SYNC_SETTINGS
pm grant "com.google.android.syncadapters.contacts" android.permission.READ_SYNC_STATS
pm grant "com.google.android.syncadapters.contacts" android.permission.RECEIVE_BOOT_COMPLETED
pm grant "com.google.android.syncadapters.contacts" android.permission.SUBSCRIBED_FEEDS_READ
pm grant "com.google.android.syncadapters.contacts" android.permission.SUBSCRIBED_FEEDS_WRITE
pm grant "com.google.android.syncadapters.contacts" android.permission.USE_CREDENTIALS
pm grant "com.google.android.syncadapters.contacts" android.permission.WAKE_LOCK
pm grant "com.google.android.syncadapters.contacts" android.permission.WRITE_CONTACTS
pm grant "com.google.android.syncadapters.contacts" android.permission.WRITE_SYNC_SETTINGS
pm grant "com.google.android.syncadapters.contacts" com.google.android.gms.permission.CONTACTS_SYNC_DELEGATION
pm grant "com.google.android.syncadapters.contacts" com.google.android.googleapps.permission.GOOGLE_AUTH
pm grant "com.google.android.syncadapters.contacts" com.google.android.googleapps.permission.GOOGLE_AUTH.cp
pm grant "com.google.android.syncadapters.contacts" com.google.android.providers.gsf.permission.READ_GSERVICES
pm grant "com.google.android.syncadapters.contacts" com.google.android.providers.gsf.permission.WRITE_GSERVICES
pm grant "com.google.android.syncadapters.contacts" com.google.android.syncadapters.contacts.permission.GAL_SEARCH
pm grant "com.google.android.syncadapters.calendar" android.permission.ACCESS_NETWORK_STATE
pm grant "com.google.android.syncadapters.calendar" android.permission.INTERNET
pm grant "com.google.android.syncadapters.calendar" android.permission.READ_CALENDAR
pm grant "com.google.android.syncadapters.calendar" android.permission.READ_SYNC_SETTINGS
pm grant "com.google.android.syncadapters.calendar" android.permission.READ_SYNC_STATS
pm grant "com.google.android.syncadapters.calendar" android.permission.RECEIVE_BOOT_COMPLETED
pm grant "com.google.android.syncadapters.calendar" android.permission.SUBSCRIBED_FEEDS_READ
pm grant "com.google.android.syncadapters.calendar" android.permission.SUBSCRIBED_FEEDS_WRITE
pm grant "com.google.android.syncadapters.calendar" android.permission.USE_CREDENTIALS
pm grant "com.google.android.syncadapters.calendar" android.permission.WAKE_LOCK
pm grant "com.google.android.syncadapters.calendar" android.permission.WRITE_CALENDAR
pm grant "com.google.android.syncadapters.calendar" android.permission.WRITE_SYNC_SETTINGS
pm grant "com.google.android.syncadapters.calendar" com.google.android.c2dm.permission.RECEIVE
pm grant "com.google.android.syncadapters.calendar" com.google.android.googleapps.permission.GOOGLE_AUTH
pm grant "com.google.android.syncadapters.calendar" com.google.android.providers.gsf.permission.READ_GSERVICES